### ISSUE TITLE
Hud Models 

### ISSUE THREAD

**Issue by Armaccord** [KourGame/issues#14]
High poly Hud weapon,  Hands, Weapon Animations, Left-hand animations (grenade toss)

**Comment by Armaccord** [comment]
![handsCapture](https://user-images.githubusercontent.com/114373486/213946682-1600bb17-6f05-42dd-87b6-2df51c48d6e0.PNG)

Hud hands are nearly done, Arms and fingers need to be properly rigged. 

Hud hands are now properly weighted and IK constants are in place.

**Comment by Armaccord** [comment]
![highCapture](https://user-images.githubusercontent.com/114373486/213946546-d7054716-fa05-4930-91b6-4caaf4b0b9cd.PNG)

high poly weapon model is finished, Before creating low-poly and textures, weapon modding needs the addressed

**Comment by Armaccord** [comment]
Weapon modding for the ak 
![modsCapture](https://user-images.githubusercontent.com/114373486/213947261-559b3b24-c8b5-45f3-bb4c-5e5e8cbcec8e.PNG)

**Comment by Armaccord** [comment]
![untitleclosed2](https://user-images.githubusercontent.com/114373486/216656164-c5697c9b-db40-4605-bda6-2f2b31b6be39.png)

Hud models are now textured and modding has been refined.

**Comment by Armaccord** [comment]
https://user-images.githubusercontent.com/114373486/216656766-9827ab6b-f84f-4d40-a681-cd49f2c903af.mp4

animation actions: 
- reload 
- charge 
- breech load 
** place holder animations have been made

**Comment by Hoodgail** [comment]
Change of plans
